/*
 * Copyright 2025 CloudWeGo Authors
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package deep

import (
	"context"
	"encoding/json"
	"fmt"
	"os"
	"path/filepath"
	"sync"
	"time"

	"github.com/cloudwego/eino-ext/components/tool/commandline"
	"github.com/cloudwego/eino/adk"
	"github.com/cloudwego/eino/components/model"

	agentutils "github.com/cloudwego/ppt-agent/pkg/agent/utils"
	"github.com/cloudwego/ppt-agent/pkg/logger"
)

// tasksManifestMu protects concurrent read-modify-write of tasks.json.
// Used when multiple goroutines (e.g. HTTP handlers) call WriteTasksManifest.
var tasksManifestMu sync.Mutex

// PPTTaskConfig PPT 任务配置
type PPTTaskConfig struct {
	WorkDir       string
	TaskID        string
	Query         string // user's original topic description (for content generation in outline mode)
	Concurrency   int
	Operator      commandline.Operator
	QAModelFn     func(ctx context.Context) (model.ToolCallingChatModel, error)
	Skills        string
	SkillsDir     string // skills 目录的绝对路径，用于构造 read_file 可用的模板路径
	CompressorOpt CompressorOption
	// CompressorTracker enables summarizer token accounting in TokenTracker.
	// When set, both main model calls and summarizer calls (used for context
	// compression) are counted in the same TokenTracker, giving accurate totals.
	CompressorTracker *agentutils.TokenTracker
	Outline           *TaskOutline // 用户编排的大纲，有值时跳过 AI 规划阶段
	StyleContext      string       // 用户风格偏好上下文，用于注入到 prompt
}

// CompressorOption 定义上下文压缩中间件的配置
type CompressorOption = agentutils.CompressorOption

// CompressorConfig 压缩器配置
type CompressorConfig = agentutils.CompressorConfig

// TasksManifest PPT 任务清单
type TasksManifest struct {
	Title    string      `json:"title"`
	Theme    string      `json:"theme"`
	Template string      `json:"template,omitempty"`
	Tasks    []*TaskItem `json:"tasks"`
}

type TaskItem struct {
	TaskID      string       `json:"task_id"`
	PageIndex   int          `json:"page_index"`
	Title       string       `json:"title"`
	ContentType string       `json:"content_type"`
	Description string       `json:"description"`
	OutputFile  string       `json:"output_file"`
	Status      string       `json:"status"`
	QAReport    string       `json:"qa_report,omitempty"`
	FixAttempts int          `json:"fix_attempts,omitempty"`
	CreatedAt   string       `json:"created_at,omitempty"`
	ContentPlan *ContentPlan `json:"content_plan,omitempty"` // structured content plan generated by AI
}

func (m *TasksManifest) MustMarshalJSON() ([]byte, error) {
	data, err := json.Marshal(m)
	if err != nil {
		logger.Error("tasks_manifest_marshal_failed", "error", err.Error())
		return nil, err
	}
	return data, nil
}

func (m *TasksManifest) UnmarshalJSON(data []byte) error {
	type alias TasksManifest
	return json.Unmarshal(data, (*alias)(m))
}

func (m *TasksManifest) CompletedCount() int {
	count := 0
	for _, t := range m.Tasks {
		if t.Status == StatusDone || t.Status == StatusQADone || t.Status == StatusFixed {
			count++
		}
	}
	return count
}

func (m *TasksManifest) AllDone() bool {
	return m.CompletedCount() == len(m.Tasks) && len(m.Tasks) > 0
}

func (m *TasksManifest) NeedsFix() []*TaskItem {
	var result []*TaskItem
	for _, t := range m.Tasks {
		if t.Status == StatusQADone && t.QAReport != "" {
			result = append(result, t)
		}
	}
	return result
}

func (m *TasksManifest) PendingTasks() []*TaskItem {
	var result []*TaskItem
	for _, t := range m.Tasks {
		if t.Status == StatusPending {
			result = append(result, t)
		}
	}
	return result
}

func (m *TasksManifest) DoneTasks() []*TaskItem {
	var result []*TaskItem
	for _, t := range m.Tasks {
		if t.Status == StatusDone {
			result = append(result, t)
		}
	}
	return result
}

func (m *TasksManifest) GetTask(taskID string) *TaskItem {
	for _, t := range m.Tasks {
		if t.TaskID == taskID {
			return t
		}
	}
	return nil
}

func WriteTasksManifest(workDir string, manifest *TasksManifest) error {
	tasksManifestMu.Lock()
	defer tasksManifestMu.Unlock()

	filePath := filepath.Join(workDir, "tasks.json")
	tmpPath := filePath + ".tmp"

	// Read existing state to merge in-flight statuses.
	data, err := os.ReadFile(filePath)
	if err != nil && !os.IsNotExist(err) {
		return err
	}

	if len(data) > 0 {
		existing := &TasksManifest{}
		if err := existing.UnmarshalJSON(data); err == nil && existing.Tasks != nil && manifest.Tasks != nil {
			for i, t := range manifest.Tasks {
				if i >= len(manifest.Tasks) {
					break
				}
				for _, et := range existing.Tasks {
					if t.TaskID == et.TaskID {
						manifest.Tasks[i].Status = et.Status
						manifest.Tasks[i].QAReport = et.QAReport
						manifest.Tasks[i].FixAttempts = et.FixAttempts
						break
					}
				}
			}
		}
	}

	// Atomic write: write to tmp, then rename.
	// os.Rename is atomic on POSIX (and safe on Windows with exclusive access).
	content, err := manifest.MustMarshalJSON()
	if err != nil {
		return err
	}
	// Validate the JSON is actually valid by unmarshaling it back
	if err := json.Unmarshal(content, &TasksManifest{}); err != nil {
		return fmt.Errorf("tasks manifest produced invalid JSON: %w", err)
	}
	if err := os.WriteFile(tmpPath, content, 0644); err != nil {
		return err
	}
	if err := os.Rename(tmpPath, filePath); err != nil {
		os.Remove(tmpPath) // clean up on failure
		return err
	}
	return nil
}

func ReadTasksManifest(workDir string) (*TasksManifest, error) {
	data, err := os.ReadFile(filepath.Join(workDir, "tasks.json"))
	if err != nil {
		return nil, err
	}
	m := &TasksManifest{}
	if err := m.UnmarshalJSON(data); err != nil {
		return nil, err
	}
	return m, nil
}

// TaskOutline 用户编排的大纲结构（用于模板编排模式）
type TaskOutline struct {
	Template string         `json:"template"`
	Theme    string         `json:"theme"`
	Title    string         `json:"title"`
	Slides   []SlideOutline `json:"slides"`
}

// ContentElement describes a single content element within a slide's content plan.
type ContentElement struct {
	Type        string   `json:"type"`                  // bullet_list, numbered_list, example_box, key_point_card, image_placeholder, table, chart_placeholder, callout, quote
	Items       []string `json:"items,omitempty"`       // for bullet_list / numbered_list
	Text        string   `json:"text,omitempty"`        // for callout / quote
	Title       string   `json:"title,omitempty"`       // for example_box / key_point_card
	Description string   `json:"description,omitempty"` // for example_box / key_point_card
	LayoutHint  string   `json:"layout_hint,omitempty"` // layout hint: left-image, right-image, top-title, center
}

// ContentPlan describes the structured content layout of a single slide page.
// It is the structured counterpart of the free-text Description field.
type ContentPlan struct {
	Summary  string           `json:"summary,omitempty"`  // one-sentence core summary
	Elements []ContentElement `json:"elements,omitempty"` // content elements list
}

// SlideOutline 单页幻灯片大纲
type SlideOutline struct {
	Title       string       `json:"title"`
	ContentType string       `json:"content_type"`
	Description string       `json:"description"`
	ContentPlan *ContentPlan `json:"content_plan,omitempty"` // optional structured content plan
}

type PPTTaskStart struct {
	Runner       *adk.Runner
	Iter         *adk.AsyncIterator[*adk.AgentEvent]
	CheckpointID string
	StartTime    time.Time
}

type PPTTaskResult struct {
	Message     string
	TotalSlides int
	DoneSlides  int
	Files       []string
	Duration    time.Duration
}

// TaskStatus 常量
const (
	StatusPending    = "pending"
	StatusGenerating = "generating"
	StatusDone       = "done"
	StatusQADone     = "qa_done"
	StatusFixed      = "fixed"
)
