/*
 * Copyright 2025 CloudWeGo Authors
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package deep

import (
	"context"
	"encoding/json"
	"fmt"
	"os"
	"path/filepath"
	"strings"
	"sync"
	"time"

	"github.com/cloudwego/eino-ext/components/tool/commandline"
	"github.com/cloudwego/eino/adk"
	"github.com/cloudwego/eino/components/model"

	agentcontentplan "github.com/cloudwego/ppt-agent/pkg/agent/contentplan"
	agentintent "github.com/cloudwego/ppt-agent/pkg/agent/intent"
	agentutils "github.com/cloudwego/ppt-agent/pkg/agent/utils"
	"github.com/cloudwego/ppt-agent/pkg/logger"
	"github.com/cloudwego/ppt-agent/pkg/style"
)

// tasksManifestMu 保护 tasks.json 的并发读写，防止多个 goroutine（如 HTTP handlers）调用 WriteTasksManifest 时产生竞态
var tasksManifestMu sync.Mutex

// PPTTaskConfig PPT 任务配置
type PPTTaskConfig struct {
	WorkDir       string
	TaskID        string
	Query         string // user's original topic description (for content generation in outline mode)
	Concurrency   int
	Operator      commandline.Operator
	QAModelFn     func(ctx context.Context) (model.ToolCallingChatModel, error)
	Skills        string
	SkillsDir     string // skills 目录的绝对路径，用于构造 read_file 可用的模板路径
	CompressorOpt CompressorOption
	// CompressorTracker 启用压缩器的 token 统计
	// 设置后，主模型调用和压缩器调用（用于上下文压缩）都会被计入同一个 TokenTracker，提供准确的总数
	CompressorTracker *agentutils.TokenTracker
	RuntimeMeta       *agentutils.RuntimeMeta
	Outline           *TaskOutline // 用户编排的大纲，有值时跳过 AI 规划阶段
	StyleContext      string       // 用户风格偏好上下文，用于注入到 prompt
	EnableQA          bool         // 是否启用 QA 质检（由 ENABLE_QA 环境变量控制）

	// 智能优化字段
	UserID          int                               // 用户ID
	IntentResult    *agentintent.ClassificationResult // 意图分类结果
	RoutingDecision *agentintent.RoutingDecision      // 路由决策
	EnhancedProfile *style.EnhancedProfile            // 增强版用户画像
	// LearningEngine 通过全局单例 GetLearningEngine() 获取，不再放在配置中
}

// CompressorOption 定义上下文压缩中间件的配置
type CompressorOption = agentutils.CompressorOption

// CompressorConfig 压缩器配置
type CompressorConfig = agentutils.CompressorConfig

// TasksManifest PPT 任务清单
type TasksManifest struct {
	Title    string      `json:"title"`
	Theme    string      `json:"theme"`
	Template string      `json:"template,omitempty"`
	Tasks    []*TaskItem `json:"tasks"`
}

type TaskItem struct {
	TaskID      string       `json:"task_id"`
	PageIndex   int          `json:"page_index"`
	Title       string       `json:"title"`
	ContentType string       `json:"content_type"`
	Description string       `json:"description"`
	OutputFile  string       `json:"output_file"`
	Status      string       `json:"status"`
	QAReport    string       `json:"qa_report,omitempty"`
	FixAttempts int          `json:"fix_attempts,omitempty"`
	CreatedAt   string       `json:"created_at,omitempty"`
	ContentPlan *ContentPlan `json:"content_plan,omitempty"` // structured content plan generated by AI
	Background  string       `json:"background,omitempty"`   // 背景图片主题
}

type ManifestValidationReport struct {
	Total        int      `json:"total"`
	Done         int      `json:"done"`
	MissingFiles []string `json:"missing_files,omitempty"`
	PendingTasks []string `json:"pending_tasks,omitempty"`
	Invalid      bool     `json:"invalid"`
}

func (m *TasksManifest) MustMarshalJSON() ([]byte, error) {
	data, err := json.Marshal(m)
	if err != nil {
		logger.Error("tasks_manifest_marshal_failed", "error", err.Error())
		return nil, err
	}
	return data, nil
}

func (m *TasksManifest) UnmarshalJSON(data []byte) error {
	type alias TasksManifest
	return json.Unmarshal(data, (*alias)(m))
}

func (m *TasksManifest) CompletedCount() int {
	count := 0
	for _, t := range m.Tasks {
		if t.Status == StatusDone || t.Status == StatusQADone || t.Status == StatusFixed {
			count++
		}
	}
	return count
}

func (m *TasksManifest) AllDone() bool {
	return m.CompletedCount() == len(m.Tasks) && len(m.Tasks) > 0
}

func (m *TasksManifest) NeedsFix() []*TaskItem {
	var result []*TaskItem
	for _, t := range m.Tasks {
		if t.Status == StatusQADone && t.QAReport != "" {
			result = append(result, t)
		}
	}
	return result
}

func (m *TasksManifest) PendingTasks() []*TaskItem {
	var result []*TaskItem
	for _, t := range m.Tasks {
		if t.Status == StatusPending {
			result = append(result, t)
		}
	}
	return result
}

func (m *TasksManifest) DoneTasks() []*TaskItem {
	var result []*TaskItem
	for _, t := range m.Tasks {
		if t.Status == StatusDone {
			result = append(result, t)
		}
	}
	return result
}

func (m *TasksManifest) GetTask(taskID string) *TaskItem {
	for _, t := range m.Tasks {
		if t.TaskID == taskID {
			return t
		}
	}
	return nil
}

func WriteTasksManifest(workDir string, manifest *TasksManifest) error {
	tasksManifestMu.Lock()
	defer tasksManifestMu.Unlock()

	filePath := filepath.Join(workDir, "tasks.json")
	tmpPath := filePath + ".tmp"

	// 读取现有数据以补齐调用方没有携带的运行时字段。调用方显式传入的新
	// status/qa_report/fix_attempts 必须被尊重，否则 done 会被旧的 pending 覆盖。
	data, err := os.ReadFile(filePath)
	if err != nil && !os.IsNotExist(err) {
		return err
	}

	if len(data) > 0 {
		existing := &TasksManifest{}
		if err := existing.UnmarshalJSON(data); err == nil && existing.Tasks != nil && manifest.Tasks != nil {
			for i, t := range manifest.Tasks {
				for _, et := range existing.Tasks {
					if t.TaskID == et.TaskID {
						if t.Status == "" {
							manifest.Tasks[i].Status = et.Status
						}
						if t.QAReport == "" {
							manifest.Tasks[i].QAReport = et.QAReport
						}
						if t.FixAttempts == 0 {
							manifest.Tasks[i].FixAttempts = et.FixAttempts
						}
						if t.CreatedAt == "" {
							manifest.Tasks[i].CreatedAt = et.CreatedAt
						}
						break
					}
				}
			}
		}
	}

	// 原子写入：先写入临时文件，然后重命名
	// os.Rename is atomic on POSIX (and safe on Windows with exclusive access).
	content, err := manifest.MustMarshalJSON()
	if err != nil {
		return err
	}
	// Validate the JSON is actually valid by unmarshaling it back
	if err := json.Unmarshal(content, &TasksManifest{}); err != nil {
		return fmt.Errorf("tasks manifest produced invalid JSON: %w", err)
	}
	if err := os.WriteFile(tmpPath, content, 0644); err != nil {
		return err
	}
	if err := os.Rename(tmpPath, filePath); err != nil {
		os.Remove(tmpPath) // clean up on failure
		return err
	}
	return nil
}

// ReconcileTasksManifestOutputFiles normalizes uniquely identifiable page
// artifacts to their declared output_file and marks present outputs as done.
func ReconcileTasksManifestOutputFiles(workDir string) (*TasksManifest, error) {
	manifest, err := ReadTasksManifest(workDir)
	if err != nil || manifest == nil {
		return manifest, err
	}
	changed := false
	for _, t := range manifest.Tasks {
		if t == nil || t.OutputFile == "" {
			continue
		}
		ready, err := reconcileTaskOutputFile(workDir, t)
		if err != nil {
			return nil, err
		}
		if ready && t.Status != StatusDone && t.Status != StatusQADone && t.Status != StatusFixed {
			t.Status = StatusDone
			changed = true
		}
	}
	if changed {
		if err := WriteTasksManifest(workDir, manifest); err != nil {
			return nil, err
		}
	}
	return manifest, nil
}

func reconcileTaskOutputFile(workDir string, task *TaskItem) (bool, error) {
	targetPath := filepath.Join(workDir, task.OutputFile)
	if _, err := os.Stat(targetPath); err == nil {
		return true, nil
	} else if !os.IsNotExist(err) {
		return false, err
	}

	candidates, err := pageOutputCandidates(workDir, task.PageIndex)
	if err != nil {
		return false, err
	}
	if len(candidates) != 1 {
		return false, nil
	}

	sourceName := candidates[0]
	sourcePath := filepath.Join(workDir, sourceName)
	if err := os.Rename(sourcePath, targetPath); err != nil {
		return false, fmt.Errorf("normalize output file %q to %q: %w", sourceName, task.OutputFile, err)
	}
	if err := renameRenderedThumbnail(workDir, sourceName, task.OutputFile); err != nil {
		return false, err
	}
	return true, nil
}

func pageOutputCandidates(workDir string, pageIndex int) ([]string, error) {
	if pageIndex <= 0 {
		return nil, nil
	}
	entries, err := os.ReadDir(workDir)
	if err != nil {
		return nil, err
	}
	underscorePrefix := fmt.Sprintf("%d_", pageIndex)
	dashPrefix := fmt.Sprintf("%d-", pageIndex)
	var candidates []string
	for _, entry := range entries {
		name := entry.Name()
		lowerName := strings.ToLower(name)
		if entry.IsDir() || filepath.Ext(lowerName) != ".pptx" {
			continue
		}
		if strings.HasPrefix(name, underscorePrefix) || strings.HasPrefix(name, dashPrefix) {
			candidates = append(candidates, name)
		}
	}
	return candidates, nil
}

func renameRenderedThumbnail(workDir, sourceFile, targetFile string) error {
	sourceStem := strings.TrimSuffix(filepath.Base(sourceFile), filepath.Ext(sourceFile))
	targetStem := strings.TrimSuffix(filepath.Base(targetFile), filepath.Ext(targetFile))
	if sourceStem == targetStem {
		return nil
	}
	qaDir := filepath.Join(workDir, "qa_images")
	sourcePath := filepath.Join(qaDir, sourceStem+".jpg")
	targetPath := filepath.Join(qaDir, targetStem+".jpg")
	if _, err := os.Stat(sourcePath); err != nil {
		if os.IsNotExist(err) {
			return nil
		}
		return err
	}
	if _, err := os.Stat(targetPath); err == nil {
		return nil
	} else if !os.IsNotExist(err) {
		return err
	}
	if err := os.Rename(sourcePath, targetPath); err != nil {
		return fmt.Errorf("normalize thumbnail %q to %q: %w", filepath.Base(sourcePath), filepath.Base(targetPath), err)
	}
	return nil
}

func ValidateTasksManifestOutcome(workDir string) (*ManifestValidationReport, error) {
	manifest, err := ReadTasksManifest(workDir)
	if err != nil {
		return nil, err
	}
	report := &ManifestValidationReport{
		Total: len(manifest.Tasks),
		Done:  manifest.CompletedCount(),
	}
	for _, t := range manifest.Tasks {
		if t == nil {
			continue
		}
		if t.Status != StatusDone && t.Status != StatusQADone && t.Status != StatusFixed {
			report.PendingTasks = append(report.PendingTasks, t.TaskID)
		}
		if t.OutputFile != "" {
			if _, err := os.Stat(filepath.Join(workDir, t.OutputFile)); err != nil {
				report.MissingFiles = append(report.MissingFiles, t.OutputFile)
			}
		}
	}
	report.Invalid = report.Total == 0 || len(report.PendingTasks) > 0 || len(report.MissingFiles) > 0
	return report, nil
}

func ReadTasksManifest(workDir string) (*TasksManifest, error) {
	data, err := os.ReadFile(filepath.Join(workDir, "tasks.json"))
	if err != nil {
		return nil, err
	}
	m := &TasksManifest{}
	if err := m.UnmarshalJSON(data); err != nil {
		return nil, err
	}
	return m, nil
}

// TaskOutline 用户编排的大纲结构（用于模板编排模式）
type TaskOutline struct {
	Template              string         `json:"template"`
	Theme                 string         `json:"theme"`
	Title                 string         `json:"title"`
	ContentMode           string         `json:"content_mode,omitempty"`
	UseBackground         bool           `json:"use_background,omitempty"`
	RecommendedBackground string         `json:"recommended_background,omitempty"`
	RecommendationReason  string         `json:"recommendation_reason,omitempty"`
	Slides                []SlideOutline `json:"slides"`
	BackgroundOptions     *struct {
		Themes []string `json:"themes"`
		Labels []string `json:"labels"`
	} `json:"background_options,omitempty"` // 全局背景选项
}

const (
	OutlineContentModeTemplateScaffold = "template_scaffold"
	OutlineContentModeUserOutline      = "user_outline"
)

// ContentElement 描述幻灯片内容计划中的单个内容元素
type ContentElement struct {
	Type        string   `json:"type"`                  // bullet_list, numbered_list, example_box, key_point_card, image_placeholder, table, chart_placeholder, callout, quote
	Items       []string `json:"items,omitempty"`       // for bullet_list / numbered_list
	Text        string   `json:"text,omitempty"`        // for callout / quote
	Title       string   `json:"title,omitempty"`       // for example_box / key_point_card
	Description string   `json:"description,omitempty"` // for example_box / key_point_card
	LayoutHint  string   `json:"layout_hint,omitempty"` // layout hint: left-image, right-image, top-title, center
}

func (e *ContentElement) UnmarshalJSON(data []byte) error {
	var raw struct {
		Type        string          `json:"type"`
		Items       json.RawMessage `json:"items"`
		Text        string          `json:"text"`
		Title       string          `json:"title"`
		Description string          `json:"description"`
		LayoutHint  string          `json:"layout_hint"`
	}
	if err := json.Unmarshal(data, &raw); err != nil {
		return err
	}
	items, err := agentcontentplan.DecodeItems(raw.Items)
	if err != nil {
		return fmt.Errorf("content_plan element items: %w", err)
	}
	*e = ContentElement{
		Type: raw.Type, Items: items, Text: raw.Text, Title: raw.Title,
		Description: raw.Description, LayoutHint: raw.LayoutHint,
	}
	return nil
}

// ContentPlan 描述单页幻灯片的内容结构化布局
// 是 free-text Description 字段的结构化对应物
type ContentPlan struct {
	Summary  string           `json:"summary,omitempty"`  // one-sentence core summary
	Elements []ContentElement `json:"elements,omitempty"` // content elements list
}

// SlideOutline 单页幻灯片大纲
type SlideOutline struct {
	Title       string       `json:"title"`
	ContentType string       `json:"content_type"`
	Description string       `json:"description"`
	ContentPlan *ContentPlan `json:"content_plan,omitempty"` // optional structured content plan
	Background  string       `json:"background,omitempty"`   // 背景图片主题
}

type PPTTaskStart struct {
	Runner       *adk.Runner
	Iter         *adk.AsyncIterator[*adk.AgentEvent]
	CheckpointID string
	StartTime    time.Time
}

type PPTTaskResult struct {
	Message     string
	TotalSlides int
	DoneSlides  int
	Files       []string
	Duration    time.Duration
}

// TaskStatus 常量
const (
	StatusPending    = "pending"
	StatusGenerating = "generating"
	StatusDone       = "done"
	StatusQADone     = "qa_done"
	StatusFixed      = "fixed"
)
