<script setup lang="ts">
import { onMounted, ref } from 'vue'
import { Eye, EyeOff, KeyRound, LoaderCircle, Trash2, X } from 'lucide-vue-next'
import { deleteUserApiKey, fetchUserApiKeyStatus, updateUserApiKey } from '../api'

const emit = defineEmits<{ close: [] }>()
const provider = ref('ark'); const apiKey = ref(''); const masked = ref(''); const configured = ref(false); const busy = ref(false); const error = ref(''); const notice = ref(''); const visible = ref(false); const confirmingRemoval = ref(false)
async function load() { try { const status = await fetchUserApiKeyStatus(); provider.value = status.provider || status.default_provider || 'ark'; masked.value = status.masked_key; configured.value = status.configured } catch (e) { error.value = e instanceof Error ? e.message : '无法读取 Key 状态' } }
async function save() { if (!apiKey.value.trim()) { error.value = '请输入 API Key'; return }; busy.value = true; error.value = ''; notice.value = ''; try { const status = await updateUserApiKey(apiKey.value.trim(), provider.value); configured.value = status.configured; masked.value = status.masked_key; apiKey.value = ''; notice.value = '已保存，界面只显示掩码。' } catch (e) { error.value = e instanceof Error ? e.message : '保存失败' } finally { busy.value = false } }
async function remove() { if (!configured.value) return; busy.value = true; error.value = ''; try { await deleteUserApiKey(); configured.value = false; masked.value = ''; notice.value = '已删除账户 Key。' } catch (e) { error.value = e instanceof Error ? e.message : '删除失败' } finally { busy.value = false; confirmingRemoval.value = false } }
onMounted(load)
</script>

<template><div class="dialog-backdrop" role="presentation" @click.self="emit('close')"><section class="key-dialog" role="dialog" aria-modal="true" aria-label="模型 Key 设置"><header><span><KeyRound :size="18" />模型 Key</span><button aria-label="关闭" @click="emit('close')"><X :size="18" /></button></header><p>使用自己的模型供应商 Key。Key 仅提交给服务端加密保存，之后不会再完整显示。</p><div v-if="configured" class="configured"><span>当前已配置</span><code>{{ masked }}</code></div><label>供应商<select v-model="provider"><option value="ark">火山 Ark</option><option value="deepseek">DeepSeek</option><option value="qwen">通义千问</option><option value="siliconflow">硅基流动</option><option value="openai">OpenAI Compatible</option></select></label><label>新的 API Key<div class="secret"><input v-model="apiKey" :type="visible ? 'text' : 'password'" autocomplete="off" placeholder="粘贴新的 API Key" /><button type="button" :aria-label="visible ? '隐藏 Key' : '显示 Key'" @click="visible = !visible"><EyeOff v-if="visible" :size="16" /><Eye v-else :size="16" /></button></div></label><p v-if="error" class="error">{{ error }}</p><p v-if="notice" class="notice">{{ notice }}</p><div v-if="confirmingRemoval" class="remove-confirm" role="alert"><p>删除当前账户保存的模型 Key？此操作无法恢复。</p><button type="button" :disabled="busy" @click="confirmingRemoval=false">取消</button><button type="button" class="delete" :disabled="busy" @click="remove">确认删除</button></div><footer><button v-if="configured && !confirmingRemoval" type="button" class="delete" :disabled="busy" @click="confirmingRemoval=true"><Trash2 :size="15" />删除</button><button type="button" class="save" :disabled="busy" @click="save"><LoaderCircle v-if="busy" :size="15" class="spin" />{{ busy ? '正在保存' : '保存 Key' }}</button></footer></section></div></template>
<style scoped>
.dialog-backdrop{position:fixed;z-index:60;inset:0;display:grid;place-items:center;padding:20px;background:rgba(2,13,21,.65);backdrop-filter:blur(7px)}.key-dialog{width:min(100%,460px);padding:22px;color:#def0ef;background:#f3f5ed;border:1px solid #d7e1da;border-radius:12px;box-shadow:0 28px 70px rgba(0,0,0,.35)}.key-dialog header{display:flex;justify-content:space-between;align-items:center;color:#103541;font:700 19px 'Noto Serif SC',serif}.key-dialog header span{display:flex;align-items:center;gap:8px}.key-dialog header button{display:grid;place-items:center;border:0;color:#436069;background:transparent}.key-dialog>p{margin:12px 0 18px;color:#5d7276;font-size:13px;line-height:1.7}.configured{display:flex;justify-content:space-between;align-items:center;margin-bottom:16px;padding:9px 10px;color:#236b66;background:#d8ede5;border-radius:6px;font-size:12px}.configured code{color:#35656b;font:11px 'DM Mono',monospace}.key-dialog label{display:block;margin-top:13px;color:#38575d;font-size:12px;font-weight:700}.key-dialog select,.secret{width:100%;height:42px;margin-top:6px;border:1px solid #bdcdc6;border-radius:6px;color:#183a43;background:#fbfcf8}.key-dialog select{padding:0 10px}.secret{display:flex;align-items:center}.secret input{min-width:0;flex:1;height:100%;padding:0 10px;border:0;outline:0;color:#183a43;background:transparent}.secret button{display:grid;place-items:center;width:38px;height:100%;border:0;color:#547078;background:transparent}.error,.notice{margin:10px 0 0!important;font-size:12px!important}.error{color:#a73333!important}.notice{color:#187269!important}.remove-confirm{margin-top:14px;padding:11px;border:1px solid #d7b4ae;border-radius:6px;color:#6b3837;background:#fff6f3}.remove-confirm p{margin:0 0 9px;font-size:12px;line-height:1.5}.remove-confirm button{margin-right:7px;padding:6px 9px;border:1px solid #bdcdc6;border-radius:5px;color:#38575d;background:#fbfcf8;font-size:12px}.remove-confirm .delete{color:#aa3d3b;border-color:#d7b4ae;background:transparent}.key-dialog footer{display:flex;justify-content:space-between;gap:10px;margin-top:21px}.key-dialog footer button{display:flex;align-items:center;justify-content:center;gap:6px;min-height:39px;border-radius:6px;padding:0 13px;font-weight:700}.delete{color:#aa3d3b;background:transparent;border:1px solid #d7b4ae}.save{margin-left:auto;color:#effbf6;background:#0e5961;border:0}.save:disabled,.delete:disabled{opacity:.55}.spin{animation:spin 1s linear infinite}@keyframes spin{to{transform:rotate(360deg)}}
</style>
