/*
 * Copyright 2025 CloudWeGo Authors
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package deck

import (
	"encoding/json"
	"fmt"
	"os"
	"path/filepath"
	"strings"
	"sync"
	"time"

	"github.com/cloudwego/eino-ext/components/tool/commandline"
	"github.com/cloudwego/eino/adk"

	agentcontentplan "github.com/cloudwego/ppt-agent/pkg/agent/contentplan"
	agentutils "github.com/cloudwego/ppt-agent/pkg/agent/utils"
	"github.com/cloudwego/ppt-agent/pkg/logger"
)

// tasksManifestMu 保护 tasks.json 的并发读写，防止多个 goroutine（如 HTTP handlers）调用 WriteTasksManifest 时产生竞态
var tasksManifestMu sync.Mutex

// PPTTaskConfig PPT 任务配置
type PPTTaskConfig struct {
	WorkDir       string
	TaskID        string
	Query         string // user's original topic description (for content generation in outline mode)
	Concurrency   int
	Operator      commandline.Operator
	SkillsDir     string // skills 目录的绝对路径，用于构造 read_file 可用的模板路径
	ModelAPIKey   string // account-level model key override; empty uses env fallback
	ModelProvider string // provider that owns ModelAPIKey; empty keeps legacy Ark behavior
	// DisableImageSearch lets isolated evaluation runs avoid registering the
	// network-backed image search tool. Production tasks keep the default false.
	DisableImageSearch bool
	CompressorOpt      CompressorOption
	// CompressorTracker 启用压缩器的 token 统计
	// 设置后，主模型调用和压缩器调用（用于上下文压缩）都会被计入同一个 TokenTracker，提供准确的总数
	CompressorTracker *agentutils.TokenTracker
	RuntimeMeta       *agentutils.RuntimeMeta
	Outline           *TaskOutline // 用户编排的大纲；作为 Planner 草稿约束，不跳过规划与审查
	Intent            string
	ConversationID    string
	SourceMessageID   string
	ParentTaskID      string

	UserID int // 用户ID
}

// CompressorOption 定义上下文压缩中间件的配置
type CompressorOption = agentutils.CompressorOption

// CompressorConfig 压缩器配置
type CompressorConfig = agentutils.CompressorConfig

// TasksManifest PPT 任务清单
type TasksManifest struct {
	Title        string         `json:"title"`
	ContentBank  map[string]any `json:"content_bank,omitempty"`
	Sections     []DeckSection  `json:"sections,omitempty"`
	VisualPolicy *VisualPolicy  `json:"visual_policy,omitempty"`
	Tasks        []*TaskItem    `json:"tasks"`
}

// VisualPolicy declares whether this deck requires external visual assets.
// Missing policy defaults to required so regular decks cannot silently lose
// their backgrounds; mode=none is an explicit benchmark/test exemption.
type VisualPolicy struct {
	Mode          string   `json:"mode,omitempty"` // required | optional | none
	MinImagePages int      `json:"min_image_pages,omitempty"`
	RequiredRoles []string `json:"required_roles,omitempty"`
	Reason        string   `json:"reason,omitempty"`
}

type TaskItem struct {
	TaskID        string       `json:"task_id"`
	PageIndex     int          `json:"page_index"`
	SectionID     string       `json:"section_id,omitempty"`
	SectionTitle  string       `json:"section_title,omitempty"`
	Title         string       `json:"title"`
	ContentType   string       `json:"content_type"`
	LayoutVariant string       `json:"layout_variant,omitempty"`
	PageIntent    string       `json:"page_intent,omitempty"`
	EvidenceRefs  []string     `json:"evidence_refs,omitempty"`
	OutputFile    string       `json:"output_file"`
	Status        string       `json:"status"`
	ContentPlan   *ContentPlan `json:"content_plan,omitempty"` // structured content plan generated by AI
}

type ManifestValidationReport struct {
	Total        int      `json:"total"`
	Done         int      `json:"done"`
	MissingFiles []string `json:"missing_files,omitempty"`
	PendingTasks []string `json:"pending_tasks,omitempty"`
	Invalid      bool     `json:"invalid"`
}

func (m *TasksManifest) MustMarshalJSON() ([]byte, error) {
	data, err := json.Marshal(m)
	if err != nil {
		logger.Error("tasks_manifest_marshal_failed", "error", err.Error())
		return nil, err
	}
	return data, nil
}

func (m *TasksManifest) UnmarshalJSON(data []byte) error {
	type alias TasksManifest
	return json.Unmarshal(data, (*alias)(m))
}

func (m *TasksManifest) CompletedCount() int {
	count := 0
	for _, t := range m.Tasks {
		if t.Status == StatusDone || t.Status == StatusQADone || t.Status == StatusFixed {
			count++
		}
	}
	return count
}

func (m *TasksManifest) AllDone() bool {
	return m.CompletedCount() == len(m.Tasks) && len(m.Tasks) > 0
}

func (m *TasksManifest) NeedsFix() []*TaskItem {
	return nil
}

func (m *TasksManifest) PendingTasks() []*TaskItem {
	var result []*TaskItem
	for _, t := range m.Tasks {
		if t.Status == StatusPending {
			result = append(result, t)
		}
	}
	return result
}

func (m *TasksManifest) DoneTasks() []*TaskItem {
	var result []*TaskItem
	for _, t := range m.Tasks {
		if t.Status == StatusDone {
			result = append(result, t)
		}
	}
	return result
}

func (m *TasksManifest) GetTask(taskID string) *TaskItem {
	for _, t := range m.Tasks {
		if t.TaskID == taskID {
			return t
		}
	}
	return nil
}

func WriteTasksManifest(workDir string, manifest *TasksManifest) error {
	tasksManifestMu.Lock()
	defer tasksManifestMu.Unlock()

	// 读取现有数据以补齐调用方没有携带的运行时状态。调用方显式传入的新
	// status 必须被尊重，否则 done 会被旧的 pending 覆盖。
	data, err := os.ReadFile(filepath.Join(workDir, "tasks.json"))
	if err != nil && !os.IsNotExist(err) {
		return err
	}

	if len(data) > 0 {
		existing := &TasksManifest{}
		if err := existing.UnmarshalJSON(data); err == nil && existing.Tasks != nil && manifest.Tasks != nil {
			for i, t := range manifest.Tasks {
				for _, et := range existing.Tasks {
					if t.TaskID == et.TaskID {
						if t.Status == "" {
							manifest.Tasks[i].Status = et.Status
						}
						break
					}
				}
			}
		}
	}

	return writeTasksManifestUnlocked(workDir, manifest)
}

func writeTasksManifestUnlocked(workDir string, manifest *TasksManifest) error {
	filePath := filepath.Join(workDir, "tasks.json")
	tmpPath := filePath + ".tmp"

	content, err := manifest.MustMarshalJSON()
	if err != nil {
		return err
	}
	if err := json.Unmarshal(content, &TasksManifest{}); err != nil {
		return fmt.Errorf("tasks manifest produced invalid JSON: %w", err)
	}
	if err := os.WriteFile(tmpPath, content, 0644); err != nil {
		return err
	}
	if err := os.Rename(tmpPath, filePath); err != nil {
		os.Remove(tmpPath)
		return err
	}
	return nil
}

// PatchTaskRuntimeFields updates one task's runtime-only fields under the same
// manifest lock used by WriteTasksManifest. Worker-pool rendering calls this
// instead of rewriting the full planning contract from concurrent goroutines.
func PatchTaskRuntimeFields(workDir, taskID, status string) error {
	tasksManifestMu.Lock()
	defer tasksManifestMu.Unlock()

	data, err := os.ReadFile(filepath.Join(workDir, "tasks.json"))
	if err != nil {
		return err
	}
	manifest := &TasksManifest{}
	if err := manifest.UnmarshalJSON(data); err != nil {
		return err
	}
	var found bool
	for _, task := range manifest.Tasks {
		if task == nil || task.TaskID != taskID {
			continue
		}
		found = true
		if status != "" {
			task.Status = status
		}
		break
	}
	if !found {
		return fmt.Errorf("task_id %s not found in tasks.json", taskID)
	}
	return writeTasksManifestUnlocked(workDir, manifest)
}

// ReconcileTasksManifestOutputFiles normalizes uniquely identifiable page
// artifacts to their declared output_file and marks present outputs as done.
func ReconcileTasksManifestOutputFiles(workDir string) (*TasksManifest, error) {
	manifest, err := ReadTasksManifest(workDir)
	if err != nil || manifest == nil {
		return manifest, err
	}
	changed := false
	for _, t := range manifest.Tasks {
		if t == nil || t.OutputFile == "" {
			continue
		}
		ready, err := reconcileTaskOutputFile(workDir, t)
		if err != nil {
			return nil, err
		}
		if ready && t.Status != StatusDone && t.Status != StatusQADone && t.Status != StatusFixed {
			t.Status = StatusDone
			changed = true
		}
	}
	if changed {
		if err := WriteTasksManifest(workDir, manifest); err != nil {
			return nil, err
		}
	}
	return manifest, nil
}

func reconcileTaskOutputFile(workDir string, task *TaskItem) (bool, error) {
	targetPath := filepath.Join(workDir, task.OutputFile)
	if _, err := os.Stat(targetPath); err == nil {
		return true, nil
	} else if !os.IsNotExist(err) {
		return false, err
	}

	candidates, err := pageOutputCandidates(workDir, task.PageIndex)
	if err != nil {
		return false, err
	}
	if len(candidates) != 1 {
		return false, nil
	}

	sourceName := candidates[0]
	sourcePath := filepath.Join(workDir, sourceName)
	if err := os.Rename(sourcePath, targetPath); err != nil {
		return false, fmt.Errorf("normalize output file %q to %q: %w", sourceName, task.OutputFile, err)
	}
	if err := renameRenderedThumbnail(workDir, sourceName, task.OutputFile); err != nil {
		return false, err
	}
	return true, nil
}

func pageOutputCandidates(workDir string, pageIndex int) ([]string, error) {
	if pageIndex <= 0 {
		return nil, nil
	}
	entries, err := os.ReadDir(workDir)
	if err != nil {
		return nil, err
	}
	underscorePrefix := fmt.Sprintf("%d_", pageIndex)
	dashPrefix := fmt.Sprintf("%d-", pageIndex)
	var candidates []string
	for _, entry := range entries {
		name := entry.Name()
		lowerName := strings.ToLower(name)
		if entry.IsDir() || filepath.Ext(lowerName) != ".pptx" {
			continue
		}
		if strings.HasPrefix(name, underscorePrefix) || strings.HasPrefix(name, dashPrefix) {
			candidates = append(candidates, name)
		}
	}
	return candidates, nil
}

func renameRenderedThumbnail(workDir, sourceFile, targetFile string) error {
	sourceStem := strings.TrimSuffix(filepath.Base(sourceFile), filepath.Ext(sourceFile))
	targetStem := strings.TrimSuffix(filepath.Base(targetFile), filepath.Ext(targetFile))
	if sourceStem == targetStem {
		return nil
	}
	qaDir := filepath.Join(workDir, "qa_images")
	sourcePath := filepath.Join(qaDir, sourceStem+".jpg")
	targetPath := filepath.Join(qaDir, targetStem+".jpg")
	if _, err := os.Stat(sourcePath); err != nil {
		if os.IsNotExist(err) {
			return nil
		}
		return err
	}
	if _, err := os.Stat(targetPath); err == nil {
		return nil
	} else if !os.IsNotExist(err) {
		return err
	}
	if err := os.Rename(sourcePath, targetPath); err != nil {
		return fmt.Errorf("normalize thumbnail %q to %q: %w", filepath.Base(sourcePath), filepath.Base(targetPath), err)
	}
	return nil
}

func ValidateTasksManifestOutcome(workDir string) (*ManifestValidationReport, error) {
	manifest, err := ReadTasksManifest(workDir)
	if err != nil {
		return nil, err
	}
	report := &ManifestValidationReport{
		Total: len(manifest.Tasks),
		Done:  manifest.CompletedCount(),
	}
	for _, t := range manifest.Tasks {
		if t == nil {
			continue
		}
		if t.Status != StatusDone && t.Status != StatusQADone && t.Status != StatusFixed {
			report.PendingTasks = append(report.PendingTasks, t.TaskID)
		}
		if t.OutputFile != "" {
			if _, err := os.Stat(filepath.Join(workDir, t.OutputFile)); err != nil {
				report.MissingFiles = append(report.MissingFiles, t.OutputFile)
			}
		}
	}
	report.Invalid = report.Total == 0 || len(report.PendingTasks) > 0 || len(report.MissingFiles) > 0
	return report, nil
}

func ReadTasksManifest(workDir string) (*TasksManifest, error) {
	data, err := os.ReadFile(filepath.Join(workDir, "tasks.json"))
	if err != nil {
		return nil, err
	}
	m := &TasksManifest{}
	if err := m.UnmarshalJSON(data); err != nil {
		return nil, err
	}
	return m, nil
}

// TaskOutline 用户编排的大纲结构（用于模板编排模式）
type TaskOutline struct {
	Title                string         `json:"title"`
	ContentMode          string         `json:"content_mode,omitempty"`
	RecommendationReason string         `json:"recommendation_reason,omitempty"`
	Slides               []SlideOutline `json:"slides"`
}

type DeckSection struct {
	ID          string `json:"id"`
	Title       string `json:"title"`
	Summary     string `json:"summary,omitempty"`
	StartPage   int    `json:"start_page"`
	EndPage     int    `json:"end_page"`
	PageCount   int    `json:"page_count,omitempty"`
	NeighborKey string `json:"neighbor_key,omitempty"`
}

const (
	OutlineContentModeUserOutline = "user_outline"
)

func decodeComponentText(data json.RawMessage) (string, error) {
	parts, err := agentcontentplan.DecodeItems(data)
	if err != nil {
		return "", err
	}
	return strings.Join(parts, "\n"), nil
}

// PlanComponent is the executable semantic unit consumed by slide compilers.
// It deliberately excludes coordinates, font sizes, colors, margins and other
// rendering details; those stay in Python generators and template contracts.
type PlanComponent struct {
	ID           string         `json:"id,omitempty"`
	Type         string         `json:"type"`
	Title        string         `json:"title,omitempty"`
	Text         string         `json:"text,omitempty"`
	Body         string         `json:"body,omitempty"`
	Items        []string       `json:"items,omitempty"`
	Emphasis     string         `json:"emphasis,omitempty"`
	Role         string         `json:"role,omitempty"`
	Relation     string         `json:"relation,omitempty"`
	Target       string         `json:"target,omitempty"`
	Icon         string         `json:"icon,omitempty"`
	Source       string         `json:"source,omitempty"`
	AssetPurpose string         `json:"asset_purpose,omitempty"`
	AssetSubject string         `json:"asset_subject,omitempty"`
	AssetQuery   string         `json:"asset_query,omitempty"`
	Composition  string         `json:"composition,omitempty"`
	Provider     string         `json:"provider,omitempty"`
	SearchStatus string         `json:"search_status,omitempty"`
	Caption      string         `json:"caption,omitempty"`
	AssetID      string         `json:"asset_id,omitempty"`
	LocalPath    string         `json:"local_path,omitempty"`
	ImageURL     string         `json:"image_url,omitempty"`
	PreviewURL   string         `json:"preview_url,omitempty"`
	SourceURL    string         `json:"source_url,omitempty"`
	Attribution  string         `json:"attribution,omitempty"`
	Data         map[string]any `json:"data,omitempty"`
}

func (c *PlanComponent) UnmarshalJSON(data []byte) error {
	var raw struct {
		ID           string          `json:"id"`
		Type         string          `json:"type"`
		Title        string          `json:"title"`
		Text         json.RawMessage `json:"text"`
		Body         json.RawMessage `json:"body"`
		Items        json.RawMessage `json:"items"`
		Emphasis     string          `json:"emphasis"`
		Role         string          `json:"role"`
		Relation     string          `json:"relation"`
		Target       string          `json:"target"`
		Icon         string          `json:"icon"`
		Source       string          `json:"source"`
		AssetPurpose string          `json:"asset_purpose"`
		AssetSubject string          `json:"asset_subject"`
		AssetQuery   string          `json:"asset_query"`
		Composition  string          `json:"composition"`
		Provider     string          `json:"provider"`
		SearchStatus string          `json:"search_status"`
		Caption      string          `json:"caption"`
		AssetID      string          `json:"asset_id"`
		LocalPath    string          `json:"local_path"`
		ImageURL     string          `json:"image_url"`
		PreviewURL   string          `json:"preview_url"`
		SourceURL    string          `json:"source_url"`
		Attribution  string          `json:"attribution"`
		Data         map[string]any  `json:"data"`
	}
	if err := json.Unmarshal(data, &raw); err != nil {
		return err
	}
	items, err := agentcontentplan.DecodeItems(raw.Items)
	if err != nil {
		return fmt.Errorf("component items: %w", err)
	}
	text, err := decodeComponentText(raw.Text)
	if err != nil {
		return fmt.Errorf("component text: %w", err)
	}
	body, err := decodeComponentText(raw.Body)
	if err != nil {
		return fmt.Errorf("component body: %w", err)
	}
	*c = PlanComponent{
		ID: raw.ID, Type: raw.Type, Title: raw.Title, Text: text, Body: body,
		Items: items, Emphasis: raw.Emphasis, Role: raw.Role, Relation: raw.Relation,
		Target: raw.Target, Icon: raw.Icon, Source: raw.Source,
		AssetPurpose: raw.AssetPurpose, AssetSubject: raw.AssetSubject,
		AssetQuery: raw.AssetQuery, Composition: raw.Composition,
		Provider: raw.Provider, SearchStatus: raw.SearchStatus,
		Caption: raw.Caption, AssetID: raw.AssetID,
		LocalPath: raw.LocalPath, ImageURL: raw.ImageURL, PreviewURL: raw.PreviewURL,
		SourceURL: raw.SourceURL, Attribution: raw.Attribution,
		Data: raw.Data,
	}
	return nil
}

type PlanReviewIssue struct {
	Code        string `json:"code"`
	Severity    string `json:"severity,omitempty"`
	Message     string `json:"message,omitempty"`
	PageIndex   int    `json:"page_index,omitempty"`
	ComponentID string `json:"component_id,omitempty"`
}

// ContentPlan 描述单页幻灯片的组件级内容规划。
type ContentPlan struct {
	Summary       string          `json:"summary,omitempty"`        // one-sentence core summary
	SlideIntent   string          `json:"slide_intent,omitempty"`   // semantic goal of this page in the deck
	SectionNumber string          `json:"section_number,omitempty"` // section_divider chapter number, not page index
	EvidenceRefs  []string        `json:"evidence_refs,omitempty"`  // refs into deck-level content_bank for granular repair
	VisualIntent  *VisualIntent   `json:"visual_intent,omitempty"`  // visual role and asset intent for this slide
	Components    []PlanComponent `json:"components,omitempty"`     // executable semantic component plan
}

// VisualIntent describes why a slide should use a given visual treatment.
type VisualIntent struct {
	Role             string `json:"role,omitempty"`              // hero_photo, supporting_photo, map, chart, icon, cards
	AssetPurpose     string `json:"asset_purpose,omitempty"`     // background, scene, evidence, decorative
	AssetSubject     string `json:"asset_subject,omitempty"`     // visual subject or semantic proxy selected for search
	AssetQuery       string `json:"asset_query,omitempty"`       // transformed provider-ready image search phrase
	Composition      string `json:"composition,omitempty"`       // wide/close-up, negative space and subject placement
	Provider         string `json:"provider,omitempty"`          // asset provider that resolved the local file
	SearchStatus     string `json:"search_status,omitempty"`     // resolved or downloaded after provider search
	PreferredVariant string `json:"preferred_variant,omitempty"` // matching layout_variant when known
	ImagePosition    string `json:"image_position,omitempty"`    // background, left, right, strip, inline
	Caption          string `json:"caption,omitempty"`           // short caption or alt text
	AssetID          string `json:"asset_id,omitempty"`          // selected local asset id when available
	LocalPath        string `json:"local_path,omitempty"`        // downloaded image path in task work dir
	ImageURL         string `json:"image_url,omitempty"`         // provider image URL for preview/trace
	PreviewURL       string `json:"preview_url,omitempty"`       // provider thumbnail URL
	SourceURL        string `json:"source_url,omitempty"`        // source page for attribution
	Attribution      string `json:"attribution,omitempty"`       // human-readable attribution
}

// SlideOutline 单页幻灯片大纲
type SlideOutline struct {
	Title         string       `json:"title"`
	ContentType   string       `json:"content_type"`
	LayoutVariant string       `json:"layout_variant,omitempty"`
	ContentPlan   *ContentPlan `json:"content_plan,omitempty"` // optional structured content plan
}

type PPTTaskStart struct {
	Runner       *adk.Runner
	Iter         *adk.AsyncIterator[*adk.AgentEvent]
	CheckpointID string
	StartTime    time.Time
}

type PPTTaskResult struct {
	Message     string
	TotalSlides int
	DoneSlides  int
	Files       []string
	Duration    time.Duration
}

// TaskStatus 常量
const (
	StatusPending    = "pending"
	StatusGenerating = "generating"
	StatusDone       = "done"
	StatusQADone     = "qa_done"
	StatusFixed      = "fixed"
	StatusFailed     = "failed"
)
