<script setup lang="ts">
import { onMounted, ref } from 'vue'
import { useRouter } from 'vue-router'
import { Activity, ShieldAlert, Users } from 'lucide-vue-next'
import AppShell from '../components/AppShell.vue'
import { fetchAdminStats, fetchAdminTasks, fetchAdminUsers, fetchMe } from '../api'
import type { AuthUser } from '../types'
const router=useRouter();const user=ref<AuthUser>();const error=ref('');const stats=ref({user_count:0,task_count:0,running_count:0});const users=ref<Array<{id:number;email:string;is_admin:boolean;created_at:string}>>([]);const tasks=ref<Array<{id:string;user_email?:string;query:string;status:string;done_count:number;total_count:number;created_at:string}>>([])
onMounted(async()=>{try{user.value=await fetchMe();if(!user.value.is_admin){error.value='当前账户没有运营后台权限。';return}[stats.value,users.value,tasks.value]=await Promise.all([fetchAdminStats(),fetchAdminUsers(),fetchAdminTasks()])}catch(e){error.value=e instanceof Error?e.message:'无法加载后台'}})
</script>
<template><AppShell title="运营后台" subtitle="查看账户、任务与运行负载" :email="user?.email" :guest="user?.is_guest" @new="router.push('/dashboard')"><main class="admin"><p v-if="error" class="error"><ShieldAlert :size="17" />{{ error }}</p><template v-else><section class="metrics"><article><Users :size="19" /><span>账户数<b>{{ stats.user_count }}</b></span></article><article><Activity :size="19" /><span>任务总数<b>{{ stats.task_count }}</b></span></article><article><span class="pulse"></span><span>正在运行<b>{{ stats.running_count }}</b></span></article></section><section class="admin-table"><header><h2>最近任务</h2><span>{{ tasks.length }} 条记录</span></header><div class="rows"><div v-for="task in tasks.slice(0,20)" :key="task.id" class="row"><span><b>{{ task.query }}</b><small>{{ task.user_email || '未知账户' }}</small></span><em :class="task.status">{{ task.status }}</em><span>{{ task.total_count ? `${task.done_count}/${task.total_count} 页` : '对话' }}</span></div></div></section><section class="admin-table"><header><h2>账户</h2><span>{{ users.length }} 个账户</span></header><div class="rows"><div v-for="account in users.slice(0,20)" :key="account.id" class="row"><span><b>{{ account.email }}</b><small>创建于 {{ new Date(account.created_at).toLocaleDateString() }}</small></span><em>{{ account.is_admin?'管理员':'成员' }}</em><span>#{{ account.id }}</span></div></div></section></template></main></AppShell></template>
<style scoped>
.admin{max-width:1050px;margin:auto;padding:35px 30px 70px}.metrics{display:grid;grid-template-columns:repeat(3,1fr);gap:14px}.metrics article{display:flex;gap:12px;align-items:start;padding:22px;border:1px solid rgba(170,211,215,.15);border-radius:8px;color:#73e2ca;background:#102735}.metrics span{color:#91aab4;font-size:12px}.metrics b{display:block;margin-top:5px;color:#f2f8f6;font:700 30px 'Noto Serif SC',serif}.pulse{width:13px;height:13px;margin-top:3px;border-radius:50%;background:#65dfc8;box-shadow:0 0 0 6px rgba(101,223,200,.11)}.admin-table{margin-top:28px;border:1px solid rgba(170,211,215,.15);border-radius:8px;overflow:hidden}.admin-table header{display:flex;justify-content:space-between;padding:15px 18px;border-bottom:1px solid rgba(170,211,215,.12)}.admin-table h2{margin:0;font:700 17px 'Noto Serif SC',serif}.admin-table header span,.row{font-size:12px;color:#829ba6}.row{display:grid;grid-template-columns:minmax(0,1fr) 110px 70px;gap:16px;padding:14px 18px;border-bottom:1px solid rgba(170,211,215,.08)}.row:last-child{border:0}.row b,.row small{display:block;overflow:hidden;text-overflow:ellipsis;white-space:nowrap}.row b{color:#d7e5e6;font-size:13px}.row small{margin-top:3px}.row em{font-style:normal;color:#8edcca}.row em.failed{color:#f3a19b}.error{display:flex;gap:8px;align-items:center;padding:14px;color:#f1aca6;background:#3c2029;border-radius:7px}@media(max-width:650px){.admin{padding:22px 16px}.metrics{grid-template-columns:1fr}.row{grid-template-columns:minmax(0,1fr) 70px}.row>span:last-child{display:none}}
</style>
