<script setup lang="ts">
import { computed, ref } from 'vue'
import { useRoute, useRouter } from 'vue-router'
import { ArrowLeft, ArrowRight, FileStack, KeyRound, Mail, UserRound } from 'lucide-vue-next'
import { login, loginAsGuest, sendCode } from '../api'

const router = useRouter(); const route = useRoute(); const email = ref(''); const secret = ref(''); const sent = ref(false); const passwordMode = ref(false); const busy = ref(false); const error = ref('')
const valid = computed(() => email.value.includes('@') && secret.value.trim().length > 0)
const next = () => String(route.query.next || '/dashboard')
async function send() { error.value=''; busy.value=true; try { await sendCode(email.value); sent.value=true } catch (e) { error.value = e instanceof Error ? e.message : '发送失败' } finally { busy.value=false } }
async function submit() { error.value=''; busy.value=true; try { await login(email.value, secret.value, passwordMode.value); router.push(next()) } catch(e) { error.value=e instanceof Error ? e.message:'登录失败' } finally { busy.value=false } }
async function guest() { error.value='';busy.value=true;try{await loginAsGuest();router.push(next())}catch(e){error.value=e instanceof Error?e.message:'访客登录失败'}finally{busy.value=false} }
</script>
<template><main class="auth-page"><RouterLink to="/" class="back"><ArrowLeft :size="16" />返回首页</RouterLink><section class="auth-panel"><div class="brand"><span><FileStack :size="22" /></span><b>Deckform</b></div><p class="overline">开始一份演示</p><h1>把你的想法<br>排成作品。</h1><p class="intro">登录后可保存会话、继续生成，并管理你的交付文件。</p><div class="switch"><button :class="{on:!passwordMode}" @click="passwordMode=false">验证码登录</button><button :class="{on:passwordMode}" @click="passwordMode=true">密码登录</button></div><form @submit.prevent="submit"><label><Mail :size="16" /><input v-model="email" type="email" autocomplete="email" placeholder="邮箱地址" /></label><label><KeyRound :size="16" /><input v-model="secret" :type="passwordMode?'password':'text'" :placeholder="passwordMode?'密码':'6 位验证码'" /></label><button v-if="!passwordMode && !sent" class="send" type="button" :disabled="busy || !email.includes('@')" @click="send">发送验证码</button><p v-if="sent && !passwordMode" class="sent">验证码已发送，请检查邮箱。</p><p v-if="error" class="error">{{ error }}</p><button class="submit" :disabled="busy || !valid">{{ busy ? '正在连接…' : '进入工作台' }}<ArrowRight :size="17" /></button></form><div class="rule"><span>或先体验</span></div><button class="guest" :disabled="busy" @click="guest"><UserRound :size="17" />以访客身份继续</button><p class="guest-hint">访客数据仅保留在当前工作区，退出后不可恢复。</p></section><aside class="auth-aside"><p>从第一行想法开始</p><div class="quote">不是把文字<br>塞进模板，<br><em>而是组织一场表达。</em></div><span>DECKFORM / CREATIVE STUDIO</span></aside></main></template>
<style scoped>
.auth-page{min-height:100vh;display:grid;grid-template-columns:minmax(0,1fr) minmax(370px,.82fr);background:#eff1e8;color:#0e2d39}.back{position:fixed;z-index:1;top:25px;left:31px;display:flex;align-items:center;gap:6px;color:#62747b;font-size:13px}.auth-panel{width:min(420px,calc(100% - 48px));margin:auto;padding:85px 0 48px}.brand{display:flex;align-items:center;gap:9px;font:700 20px 'Noto Serif SC',serif}.brand span{display:grid;place-items:center;width:33px;height:33px;color:#eff1e8;background:#0f4a55;border-radius:9px 9px 3px 9px}.overline{margin:60px 0 12px;color:#44817d;font-size:12px;font-weight:700}.auth-panel h1{margin:0;font:900 42px/1.18 'Noto Serif SC',serif;letter-spacing:-.07em}.intro{margin:17px 0 28px;color:#63777d;font-size:14px;line-height:1.8}.switch{display:flex;border-bottom:1px solid #d1dad6;margin-bottom:17px}.switch button{padding:10px 6px;border:0;border-bottom:2px solid transparent;margin-bottom:-1px;background:transparent;color:#73848a;font-size:13px}.switch button+button{margin-left:19px}.switch .on{color:#0d3f4a;border-color:#159587;font-weight:700}form label{display:flex;align-items:center;gap:10px;margin-bottom:10px;padding:0 13px;border:1px solid #c7d2ce;border-radius:6px;color:#71878a;background:#f7f8f2}input{width:100%;height:45px;border:0;outline:0;background:transparent;color:#122f37}.send{border:0;padding:0;background:transparent;color:#197f76;font-size:13px;text-decoration:underline}.sent{color:#1d8178;font-size:12px}.error{color:#b53936;font-size:13px}.submit,.guest{width:100%;height:47px;display:flex;align-items:center;justify-content:center;gap:8px;margin-top:17px;border:0;border-radius:6px;font-weight:700}.submit{color:#f2f6ef;background:#0b4551}.submit:disabled{opacity:.45}.rule{display:flex;align-items:center;gap:12px;margin:25px 0 0;color:#849595;font-size:11px}.rule:before,.rule:after{content:'';height:1px;flex:1;background:#d4dcd7}.guest{margin-top:17px;color:#174753;background:transparent;border:1px solid #b9c9c4}.guest-hint{margin:9px 0 0;color:#899798;font-size:11px;line-height:1.6;text-align:center}.auth-aside{display:flex;flex-direction:column;justify-content:center;padding:72px clamp(34px,7vw,100px);color:#ddf7f0;background:#0c3442}.auth-aside>p{margin:0 0 20px;color:#7ccfbd;font-size:13px}.quote{font:900 clamp(38px,4.5vw,66px)/1.21 'Noto Serif SC',serif;letter-spacing:-.08em}.quote em{font-style:normal;color:#70d7c1}.auth-aside span{margin-top:60px;color:#78a0a3;font:11px 'DM Mono',monospace;letter-spacing:.08em}@media(max-width:760px){.auth-page{display:block}.auth-aside{display:none}.auth-panel{padding-top:95px}.back{left:18px;top:20px}}
</style>
